baseURL = "https://kquiggins.github.io/hugo_blog/"
languageCode = "en-us"
theme = "anatole"
enableEmoji = true

[params]
title = "kens tech blog"
description = "A simple blog of my coding journey"
author = "Ken Quiggins"
profilePicture = "images/linux1.png"
mainSections = ["blog"]
readMore = true
postSectionName = "blog"

# Social Icons

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/kenneth-quiggins-225922212/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Linkedin"
url = "https://twitter.com/kash_quiggins"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Linkedin"
url = "https://github.com/KQuiggins"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  identifier = "blog"
  weight = 200
  url = "/blog/"

  
  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Portfolio"
  weight = 400
  identifier = "portfolio"
  url = "/portfolio/"








# Awards/Achievements/Certifications

[[menu.main]]
name = "Accomplishments"
weight = 500
identifier = "accomplishments"

[[menu.main]]
name = "Awards"
weight = 510
identifier = "awards"
url = "/awards/"
parent = "accomplishments"

[[menu.main]]
name = "Certifications"
weight = 520
identifier = "certifications"
url = "/certifications/"
parent = "accomplishments"



  